# Generated by Django 5.2.13 on 2026-04-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASLVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('word', 'Word'), ('letter', 'Letter')], default='word', max_length=10)),
                ('path', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'token'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'token'), name='unique_asl_video_kind_token')],
            },
        ),
    ]
